# Use the official PostgreSQL image as the base image
# FROM postgres:16.0
FROM ankane/pgvector:latest
# Set environment variables for PostgreSQL
ENV POSTGRES_DB mydatabase
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword

# Expose the PostgreSQL port (default is 5432)
EXPOSE 5432


