import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { ThemeProvider } from "@/provider/theme-provider";
import AuthProvider from "@/provider/AuthProvider";
import WebSocketProvider from "./(route)/users/chat/provider/websocket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "admin shop",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <WebSocketProvider>
            <ThemeProvider attribute="class" defaultTheme="light">
              {children}
            </ThemeProvider>
          </WebSocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
